/*
 * Copyright 2014-2019 Li Kexian
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Go module for domain and ip whois info query
 * https://www.likexian.com/
 */

package whois

import (
	"context"
	"errors"
	"fmt"
	"io/ioutil"
	"net"
	"strings"
	"time"
)

var (
	whoisRoot = map[string]string{
		"aaa":                      "whois.nic.aaa",
		"aarp":                     "whois.nic.aarp",
		"abb":                      "whois.nic.abb",
		"abbott":                   "whois.afilias-srs.net",
		"abogado":                  "whois-dub.mm-registry.com",
		"ac":                       "whois.nic.ac",
		"academy":                  "whois.donuts.co",
		"accenture":                "whois.nic.accenture",
		"accountant":               "whois.nic.accountant",
		"accountants":              "whois.donuts.co",
		"aco":                      "whois.afilias-srs.net",
		"active":                   "whois.afilias-srs.net",
		"actor":                    "whois.unitedtld.com",
		"ads":                      "domain-registry-whois.l.google.com",
		"adult":                    "whois.afilias-srs.net",
		"ae":                       "whois.aeda.net.ae",
		"aeg":                      "whois.nic.aeg",
		"aero":                     "whois.aero",
		"af":                       "whois.nic.af",
		"afl":                      "whois.nic.afl",
		"ag":                       "whois.nic.ag",
		"agency":                   "whois.donuts.co",
		"ai":                       "whois.ai",
		"aig":                      "whois.nic.aig",
		"airforce":                 "whois.unitedtld.com",
		"airtel":                   "whois.nic.airtel",
		"allfinanz":                "whois.ksregistry.net",
		"alsace":                   "whois-alsace.nic.fr",
		"am":                       "whois.amnic.net",
		"amica":                    "whois.nic.amica",
		"amsterdam":                "whois.nic.amsterdam",
		"android":                  "domain-registry-whois.l.google.com",
		"apartments":               "whois.donuts.co",
		"app":                      "whois.nic.google",
		"apple":                    "whois.afilias-srs.net",
		"aquarelle":                "whois-aquarelle.nic.fr",
		"aramco":                   "whois.nic.aramco",
		"archi":                    "whois.ksregistry.net",
		"army":                     "whois.rightside.co",
		"arpa":                     "whois.iana.org",
		"arte":                     "whois.nic.arte",
		"as":                       "whois.nic.as",
		"asia":                     "whois.nic.asia",
		"associates":               "whois.donuts.co",
		"at":                       "whois.nic.at",
		"attorney":                 "whois.rightside.co",
		"au":                       "whois.audns.net.au",
		"auction":                  "whois.donuts.co",
		"audi":                     "whois.afilias-srs.net",
		"audio":                    "whois.uniregistry.net",
		"author":                   "whois.nic.author",
		"auto":                     "whois.uniregistry.net",
		"autos":                    "whois.afilias-srs.net",
		"aw":                       "whois.nic.aw",
		"ax":                       "whois.ax",
		"axa":                      "whois.nic.axa",
		"azure":                    "whois.nic.azure",
		"band":                     "whois.rightside.co",
		"bank":                     "whois.nic.bank",
		"bar":                      "whois.nic.bar",
		"barcelona":                "whois.nic.barcelona",
		"barclaycard":              "whois.nic.barclaycard",
		"barclays":                 "whois.nic.barclays",
		"bargains":                 "whois.donuts.co",
		"bauhaus":                  "whois.nic.bauhaus",
		"bayern":                   "whois-dub.mm-registry.com",
		"bbc":                      "whois.nic.bbc",
		"bbva":                     "whois.nic.bbva",
		"bcn":                      "whois.nic.bcn",
		"be":                       "whois.dns.be",
		"beats":                    "whois.afilias-srs.net",
		"beer":                     "whois-dub.mm-registry.com",
		"bentley":                  "whois.nic.bentley",
		"berlin":                   "whois.nic.berlin",
		"best":                     "whois.nic.best",
		"bet":                      "whois.afilias.net",
		"bg":                       "whois.register.bg",
		"bharti":                   "whois.nic.bharti",
		"bi":                       "whois1.nic.bi",
		"bible":                    "whois.nic.bible",
		"bid":                      "whois.nic.bid",
		"bike":                     "whois.donuts.co",
		"bing":                     "whois.nic.bing",
		"bingo":                    "whois.donuts.co",
		"bio":                      "whois.ksregistry.net",
		"biz":                      "whois.biz",
		"bj":                       "whois.nic.bj",
		"black":                    "whois.afilias.net",
		"blackfriday":              "whois.uniregistry.net",
		"bloomberg":                "whois.nic.bloomberg",
		"blue":                     "whois.afilias.net",
		"bms":                      "whois.nic.bms",
		"bmw":                      "whois.ksregistry.net",
		"bn":                       "whois.bn",
		"bnl":                      "whois.afilias-srs.net",
		"bnpparibas":               "whois.afilias-srs.net",
		"bo":                       "whois.nic.bo",
		"boats":                    "whois.afilias-srs.net",
		"boehringer":               "whois.afilias-srs.net",
		"bom":                      "whois.gtlds.nic.br",
		"bond":                     "whois.nic.bond",
		"boo":                      "domain-registry-whois.l.google.com",
		"book":                     "whois.nic.book",
		"boots":                    "whois.nic.boots",
		"bostik":                   "whois-bostik.nic.fr",
		"bot":                      "whois.nic.bot",
		"boutique":                 "whois.donuts.co",
		"br":                       "whois.registro.br",
		"bradesco":                 "whois-cl01.mm-registry.com",
		"bridgestone":              "whois.nic.bridgestone",
		"broadway":                 "whois-cl01.mm-registry.com",
		"broker":                   "whois.nic.broker",
		"brother":                  "whois.nic.brother",
		"brussels":                 "whois.brussels.tld-box.at",
		"budapest":                 "whois-dub.mm-registry.com",
		"bugatti":                  "whois.afilias-srs.net",
		"build":                    "whois.build.aridnrs.net.au",
		"builders":                 "whois.donuts.co",
		"business":                 "whois.donuts.co",
		"buy":                      "whois.afilias-srs.net",
		"buzz":                     "whois.nic.buzz",
		"bw":                       "whois.nic.net.bw",
		"by":                       "whois.cctld.by",
		"bzh":                      "whois-bzh.nic.fr",
		"ca":                       "whois.cira.ca",
		"cab":                      "whois.donuts.co",
		"cafe":                     "whois.donuts.co",
		"cal":                      "domain-registry-whois.l.google.com",
		"call":                     "whois.nic.call",
		"camera":                   "whois.donuts.co",
		"camp":                     "whois.donuts.co",
		"cancerresearch":           "whois.nic.cancerresearch",
		"canon":                    "whois.nic.gmo",
		"capetown":                 "capetown-whois.registry.net.za",
		"capital":                  "whois.donuts.co",
		"car":                      "whois.uniregistry.net",
		"caravan":                  "whois.nic.caravan",
		"cards":                    "whois.donuts.co",
		"care":                     "whois.donuts.co",
		"career":                   "whois.nic.career",
		"careers":                  "whois.donuts.co",
		"cars":                     "whois.uniregistry.net",
		"cartier":                  "whois.nic.cartier",
		"casa":                     "whois-dub.mm-registry.com",
		"cash":                     "whois.donuts.co",
		"casino":                   "whois.donuts.co",
		"cat":                      "whois.cat",
		"catering":                 "whois.donuts.co",
		"cba":                      "whois.nic.cba",
		"cbn":                      "whois.nic.cbn",
		"cc":                       "ccwhois.verisign-grs.com",
		"cd":                       "whois.nic.cd",
		"ceb":                      "whois.afilias-srs.net",
		"center":                   "whois.donuts.co",
		"ceo":                      "whois.nic.ceo",
		"cern":                     "whois.afilias-srs.net",
		"cf":                       "whois.dot.cf",
		"cfa":                      "whois.nic.cfa",
		"cfd":                      "whois.nic.cfd",
		"ch":                       "whois.nic.ch",
		"chanel":                   "whois.nic.chanel",
		"channel":                  "domain-registry-whois.l.google.com",
		"chat":                     "whois.donuts.co",
		"cheap":                    "whois.donuts.co",
		"chloe":                    "whois.nic.chloe",
		"christmas":                "whois.uniregistry.net",
		"chrome":                   "domain-registry-whois.l.google.com",
		"church":                   "whois.donuts.co",
		"ci":                       "whois.nic.ci",
		"cipriani":                 "whois.afilias-srs.net",
		"circle":                   "whois.nic.circle",
		"cisco":                    "whois.nic.cisco",
		"citic":                    "whois.nic.citic",
		"city":                     "whois.donuts.co",
		"cityeats":                 "whois.nic.cityeats",
		"cl":                       "whois.nic.cl",
		"claims":                   "whois.donuts.co",
		"cleaning":                 "whois.donuts.co",
		"click":                    "whois.uniregistry.net",
		"clinic":                   "whois.donuts.co",
		"clothing":                 "whois.donuts.co",
		"cloud":                    "whois.nic.cloud",
		"club":                     "whois.nic.club",
		"clubmed":                  "whois.nic.clubmed",
		"cn":                       "whois.cnnic.cn",
		"co":                       "whois.nic.co",
		"coach":                    "whois.donuts.co",
		"codes":                    "whois.donuts.co",
		"coffee":                   "whois.donuts.co",
		"college":                  "whois.centralnic.com",
		"cologne":                  "whois-fe1.pdt.cologne.tango.knipp.de",
		"com":                      "whois.verisign-grs.com",
		"commbank":                 "whois.nic.commbank",
		"community":                "whois.donuts.co",
		"company":                  "whois.donuts.co",
		"computer":                 "whois.donuts.co",
		"comsec":                   "whois.nic.comsec",
		"condos":                   "whois.donuts.co",
		"construction":             "whois.donuts.co",
		"consulting":               "whois.unitedtld.com",
		"contractors":              "whois.donuts.co",
		"cooking":                  "whois-dub.mm-registry.com",
		"cool":                     "whois.donuts.co",
		"coop":                     "whois.nic.coop",
		"corsica":                  "whois-corsica.nic.fr",
		"country":                  "whois-dub.mm-registry.com",
		"coupons":                  "whois.donuts.co",
		"courses":                  "whois.aridnrs.net.au",
		"cr":                       "whois.nic.cr",
		"credit":                   "whois.donuts.co",
		"creditcard":               "whois.donuts.co",
		"creditunion":              "whois.afilias-srs.net",
		"cricket":                  "whois.nic.cricket",
		"crown":                    "whois.nic.crown",
		"crs":                      "whois.nic.crs",
		"cruises":                  "whois.donuts.co",
		"csc":                      "whois.nic.csc",
		"cuisinella":               "whois.nic.cuisinella",
		"cx":                       "whois.nic.cx",
		"cymru":                    "whois.nic.cymru",
		"cyou":                     "whois.afilias-srs.net",
		"cz":                       "whois.nic.cz",
		"dabur":                    "whois.afilias-srs.net",
		"dad":                      "domain-registry-whois.l.google.com",
		"dance":                    "whois.unitedtld.com",
		"date":                     "whois.nic.date",
		"dating":                   "whois.donuts.co",
		"datsun":                   "whois.nic.gmo",
		"day":                      "domain-registry-whois.l.google.com",
		"dclk":                     "domain-registry-whois.l.google.com",
		"de":                       "whois.denic.de",
		"deals":                    "whois.donuts.co",
		"degree":                   "whois.rightside.co",
		"delivery":                 "whois.donuts.co",
		"dell":                     "whois.nic.dell",
		"delta":                    "whois.afilias-srs.net",
		"democrat":                 "whois.unitedtld.com",
		"dental":                   "whois.donuts.co",
		"dentist":                  "whois.rightside.co",
		"desi":                     "whois.ksregistry.net",
		"design":                   "whois.centralnic.com",
		"dev":                      "domain-registry-whois.l.google.com",
		"diamonds":                 "whois.donuts.co",
		"diet":                     "whois.uniregistry.net",
		"digital":                  "whois.donuts.co",
		"direct":                   "whois.donuts.co",
		"directory":                "whois.donuts.co",
		"discount":                 "whois.donuts.co",
		"dk":                       "whois.dk-hostmaster.dk",
		"dm":                       "whois.nic.dm",
		"dnp":                      "whois.nic.dnp",
		"docs":                     "domain-registry-whois.l.google.com",
		"dog":                      "whois.donuts.co",
		"doha":                     "whois.nic.doha",
		"domains":                  "whois.donuts.co",
		"doosan":                   "whois.nic.doosan",
		"download":                 "whois.nic.download",
		"drive":                    "whois.nic.google",
		"durban":                   "durban-whois.registry.net.za",
		"dvag":                     "whois.ksregistry.net",
		"dz":                       "whois.nic.dz",
		"earth":                    "whois.nic.earth",
		"eat":                      "domain-registry-whois.l.google.com",
		"ec":                       "whois.nic.ec",
		"edu":                      "whois.educause.edu",
		"education":                "whois.donuts.co",
		"ee":                       "whois.tld.ee",
		"email":                    "whois.donuts.co",
		"emerck":                   "whois.afilias-srs.net",
		"energy":                   "whois.donuts.co",
		"engineer":                 "whois.rightside.co",
		"engineering":              "whois.donuts.co",
		"enterprises":              "whois.donuts.co",
		"epson":                    "whois.aridnrs.net.au",
		"equipment":                "whois.donuts.co",
		"erni":                     "whois.nic.erni",
		"es":                       "whois.nic.es",
		"esq":                      "domain-registry-whois.l.google.com",
		"estate":                   "whois.donuts.co",
		"eu":                       "whois.eu",
		"eurovision":               "whois.nic.eurovision",
		"eus":                      "whois.eus.coreregistry.net",
		"events":                   "whois.donuts.co",
		"everbank":                 "whois.nic.everbank",
		"exchange":                 "whois.donuts.co",
		"expert":                   "whois.donuts.co",
		"exposed":                  "whois.donuts.co",
		"express":                  "whois.donuts.co",
		"fage":                     "whois.afilias-srs.net",
		"fail":                     "whois.donuts.co",
		"fairwinds":                "whois.nic.fairwinds",
		"faith":                    "whois.nic.faith",
		"family":                   "whois.rightside.co",
		"fan":                      "whois.centralnic.com",
		"fans":                     "whois.centralnic.com",
		"farm":                     "whois.donuts.co",
		"fashion":                  "whois-dub.mm-registry.com",
		"fast":                     "whois.nic.fast",
		"feedback":                 "whois.centralnic.com",
		"ferrero":                  "whois.nic.ferrero",
		"fi":                       "whois.ficora.fi",
		"film":                     "whois.nic.film",
		"final":                    "whois.gtlds.nic.br",
		"finance":                  "whois.donuts.co",
		"financial":                "whois.donuts.co",
		"firestone":                "whois.nic.firestone",
		"firmdale":                 "whois.nic.firmdale",
		"fish":                     "whois.donuts.co",
		"fishing":                  "whois-dub.mm-registry.com",
		"fit":                      "whois-dub.mm-registry.com",
		"fitness":                  "whois.donuts.co",
		"fj":                       "whois.fj",
		"flights":                  "whois.donuts.co",
		"florist":                  "whois.donuts.co",
		"flowers":                  "whois.uniregistry.net",
		"flsmidth":                 "whois.ksregistry.net",
		"fly":                      "domain-registry-whois.l.google.com",
		"fm":                       "whois.nic.fm",
		"fo":                       "whois.nic.fo",
		"foo":                      "domain-registry-whois.l.google.com",
		"football":                 "whois.donuts.co",
		"forex":                    "whois.nic.forex",
		"forsale":                  "whois.unitedtld.com",
		"forum":                    "whois.centralnic.com",
		"foundation":               "whois.donuts.co",
		"fr":                       "whois.nic.fr",
		"frl":                      "whois.nic.frl",
		"frogans":                  "whois-frogans.nic.fr",
		"fund":                     "whois.donuts.co",
		"furniture":                "whois.donuts.co",
		"futbol":                   "whois.unitedtld.com",
		"fyi":                      "whois.donuts.co",
		"gal":                      "whois.gal.coreregistry.net",
		"gallery":                  "whois.donuts.co",
		"game":                     "whois.uniregistry.net",
		"garden":                   "whois-dub.mm-registry.com",
		"gbiz":                     "domain-registry-whois.l.google.com",
		"gd":                       "whois.adamsnames.com",
		"gdn":                      "whois.gdnregistry.com",
		"gea":                      "whois.afilias-srs.net",
		"gent":                     "whois.nic.gent",
		"genting":                  "whois.nic.genting",
		"gg":                       "whois.gg",
		"ggee":                     "whois.nic.gmo",
		"gh":                       "whois.nic.gh",
		"gi":                       "whois2.afilias-grs.net",
		"gift":                     "whois.uniregistry.net",
		"gifts":                    "whois.donuts.co",
		"gives":                    "whois.rightside.co",
		"giving":                   "whois.nic.giving",
		"gl":                       "whois.nic.gl",
		"glass":                    "whois.donuts.co",
		"gle":                      "domain-registry-whois.l.google.com",
		"global":                   "whois.afilias-srs.net",
		"globo":                    "whois.gtlds.nic.br",
		"gmail":                    "domain-registry-whois.l.google.com",
		"gmo":                      "whois.nic.gmo",
		"gmx":                      "whois-fe1.gmx.tango.knipp.de",
		"gold":                     "whois.donuts.co",
		"goldpoint":                "whois.nic.gmo",
		"golf":                     "whois.donuts.co",
		"goo":                      "whois.nic.gmo",
		"goog":                     "domain-registry-whois.l.google.com",
		"google":                   "domain-registry-whois.l.google.com",
		"gop":                      "whois-cl01.mm-registry.com",
		"got":                      "whois.nic.got",
		"gov":                      "whois.dotgov.gov",
		"gq":                       "whois.dominio.gq",
		"grainger":                 "whois.nic.grainger",
		"graphics":                 "whois.donuts.co",
		"gratis":                   "whois.donuts.co",
		"green":                    "whois.afilias.net",
		"gripe":                    "whois.donuts.co",
		"group":                    "whois.donuts.co",
		"gs":                       "whois.nic.gs",
		"gucci":                    "whois.nic.gucci",
		"guge":                     "domain-registry-whois.l.google.com",
		"guide":                    "whois.donuts.co",
		"guitars":                  "whois.uniregistry.net",
		"guru":                     "whois.donuts.co",
		"gy":                       "whois.registry.gy",
		"hamburg":                  "whois.hamburg.tld-box.at",
		"hangout":                  "domain-registry-whois.l.google.com",
		"haus":                     "whois.unitedtld.com",
		"healthcare":               "whois.donuts.co",
		"help":                     "whois.uniregistry.net",
		"here":                     "domain-registry-whois.l.google.com",
		"hermes":                   "whois.afilias-srs.net",
		"hiphop":                   "whois.uniregistry.net",
		"hitachi":                  "whois.nic.gmo",
		"hiv":                      "whois.afilias-srs.net",
		"hk":                       "whois.hkirc.hk",
		"hm":                       "whois.registry.hm",
		"hn":                       "whois2.afilias-grs.net",
		"hockey":                   "whois.donuts.co",
		"holdings":                 "whois.donuts.co",
		"holiday":                  "whois.donuts.co",
		"homedepot":                "whois.afilias-srs.net",
		"homes":                    "whois.afilias-srs.net",
		"honda":                    "whois.nic.honda",
		"horse":                    "whois-dub.mm-registry.com",
		"host":                     "whois.centralnic.com",
		"hosting":                  "whois.uniregistry.net",
		"hoteles":                  "whois.nic.hoteles",
		"hotmail":                  "whois.nic.hotmail",
		"house":                    "whois.donuts.co",
		"how":                      "domain-registry-whois.l.google.com",
		"hr":                       "whois.dns.hr",
		"hsbc":                     "whois.nic.hsbc",
		"ht":                       "whois.nic.ht",
		"hu":                       "whois.nic.hu",
		"hyundai":                  "whois.nic.hyundai",
		"ibm":                      "whois.nic.ibm",
		"icbc":                     "whois.afilias-srs.net",
		"ice":                      "whois.nic.ice",
		"icu":                      "whois.nic.icu",
		"id":                       "whois.pandi.or.id",
		"ie":                       "whois.domainregistry.ie",
		"ifm":                      "whois.nic.ifm",
		"iinet":                    "whois.aridnrs.net.au",
		"il":                       "whois.isoc.org.il",
		"im":                       "whois.nic.im",
		"immo":                     "whois.donuts.co",
		"immobilien":               "whois.unitedtld.com",
		"in":                       "whois.inregistry.net",
		"industries":               "whois.donuts.co",
		"infiniti":                 "whois.nic.gmo",
		"info":                     "whois.afilias.net",
		"ing":                      "domain-registry-whois.l.google.com",
		"ink":                      "whois.centralnic.com",
		"institute":                "whois.donuts.co",
		"insurance":                "whois.nic.insurance",
		"insure":                   "whois.donuts.co",
		"int":                      "whois.iana.org",
		"international":            "whois.donuts.co",
		"investments":              "whois.donuts.co",
		"io":                       "whois.nic.io",
		"ipiranga":                 "whois.nic.ipiranga",
		"iq":                       "whois.cmc.iq",
		"ir":                       "whois.nic.ir",
		"irish":                    "whois.afilias-srs.net",
		"is":                       "whois.isnic.is",
		"ist":                      "whois.afilias-srs.net",
		"istanbul":                 "whois.afilias-srs.net",
		"it":                       "whois.nic.it",
		"itau":                     "whois.nic.itau",
		"iwc":                      "whois.nic.iwc",
		"jaguar":                   "whois.nic.jaguar",
		"java":                     "whois.nic.java",
		"jcb":                      "whois.nic.gmo",
		"je":                       "whois.je",
		"jetzt":                    "whois.nic.jetzt",
		"jewelry":                  "whois.donuts.co",
		"jlc":                      "whois.nic.jlc",
		"jll":                      "whois.afilias-srs.net",
		"jobs":                     "jobswhois.verisign-grs.com",
		"joburg":                   "joburg-whois.registry.net.za",
		"jot":                      "whois.nic.jot",
		"joy":                      "whois.nic.joy",
		"jp":                       "whois.jprs.jp",
		"jprs":                     "whois.nic.jprs",
		"juegos":                   "whois.uniregistry.net",
		"kaufen":                   "whois.unitedtld.com",
		"kddi":                     "whois.nic.gmo",
		"ke":                       "whois.kenic.or.ke",
		"kg":                       "whois.domain.kg",
		"ki":                       "whois.nic.ki",
		"kia":                      "whois.nic.kia",
		"kim":                      "whois.afilias.net",
		"kinder":                   "whois.nic.kinder",
		"kitchen":                  "whois.donuts.co",
		"kiwi":                     "whois.dot-kiwi.com",
		"koeln":                    "whois-fe1.pdt.koeln.tango.knipp.de",
		"komatsu":                  "whois.nic.komatsu",
		"kr":                       "whois.kr",
		"krd":                      "whois.aridnrs.net.au",
		"kred":                     "whois.nic.kred",
		"ky":                       "whois.kyregistry.ky",
		"kyoto":                    "whois.nic.tokyo",
		"kz":                       "whois.nic.kz",
		"la":                       "whois.nic.la",
		"lacaixa":                  "whois.nic.lacaixa",
		"lamborghini":              "whois.afilias-srs.net",
		"lancaster":                "whois-lancaster.nic.fr",
		"land":                     "whois.donuts.co",
		"landrover":                "whois.nic.landrover",
		"lasalle":                  "whois.afilias-srs.net",
		"lat":                      "whois.nic.lat",
		"latrobe":                  "whois.nic.latrobe",
		"law":                      "whois-dub.mm-registry.com",
		"lawyer":                   "whois.rightside.co",
		"lc":                       "whois.nic.lc",
		"lds":                      "whois.afilias-srs.net",
		"lease":                    "whois.donuts.co",
		"leclerc":                  "whois-leclerc.nic.fr",
		"legal":                    "whois.donuts.co",
		"lexus":                    "whois.nic.lexus",
		"lgbt":                     "whois.afilias.net",
		"li":                       "whois.nic.li",
		"liaison":                  "whois.nic.liaison",
		"lidl":                     "whois.nic.lidl",
		"life":                     "whois.donuts.co",
		"lifestyle":                "whois.nic.lifestyle",
		"lighting":                 "whois.donuts.co",
		"like":                     "whois.nic.like",
		"limited":                  "whois.donuts.co",
		"limo":                     "whois.donuts.co",
		"linde":                    "whois.nic.linde",
		"link":                     "whois.uniregistry.net",
		"live":                     "whois.rightside.co",
		"lixil":                    "whois.nic.lixil",
		"lk":                       "whois.nic.lk",
		"loan":                     "whois.nic.loan",
		"loans":                    "whois.donuts.co",
		"lol":                      "whois.uniregistry.net",
		"london":                   "whois-lon.mm-registry.com",
		"lotte":                    "whois.nic.gmo",
		"lotto":                    "whois.afilias.net",
		"love":                     "whois.centralnic.com",
		"lt":                       "whois.domreg.lt",
		"ltd":                      "whois.donuts.co",
		"ltda":                     "whois.afilias-srs.net",
		"lu":                       "whois.dns.lu",
		"lupin":                    "whois.nic.lupin",
		"luxe":                     "whois-dub.mm-registry.com",
		"luxury":                   "whois.luxury.aridnrs.net.au",
		"lv":                       "whois.nic.lv",
		"ly":                       "whois.nic.ly",
		"ma":                       "whois.iam.net.ma",
		"madrid":                   "whois.madrid.rs.corenic.net",
		"maif":                     "whois.nic.maif",
		"maison":                   "whois.donuts.co",
		"man":                      "whois.nic.man",
		"management":               "whois.donuts.co",
		"mango":                    "whois.mango.coreregistry.net",
		"market":                   "whois.rightside.co",
		"marketing":                "whois.donuts.co",
		"markets":                  "whois.nic.markets",
		"marriott":                 "whois.afilias-srs.net",
		"mba":                      "whois.donuts.co",
		"md":                       "whois.nic.md",
		"me":                       "whois.nic.me",
		"med":                      "whois.nic.med",
		"media":                    "whois.donuts.co",
		"meet":                     "whois.afilias.net",
		"melbourne":                "whois.aridnrs.net.au",
		"meme":                     "domain-registry-whois.l.google.com",
		"memorial":                 "whois.donuts.co",
		"men":                      "whois.nic.men",
		"menu":                     "whois.nic.menu",
		"meo":                      "whois.nic.meo",
		"mg":                       "whois.nic.mg",
		"miami":                    "whois-dub.mm-registry.com",
		"microsoft":                "whois.nic.microsoft",
		"mini":                     "whois.ksregistry.net",
		"mk":                       "whois.marnet.mk",
		"ml":                       "whois.dot.ml",
		"mma":                      "whois-mma.nic.fr",
		"mn":                       "whois.nic.mn",
		"mo":                       "whois.monic.mo",
		"mobi":                     "whois.dotmobiregistry.net",
		"moda":                     "whois.unitedtld.com",
		"moe":                      "whois.nic.moe",
		"moi":                      "whois.nic.moi",
		"mom":                      "whois.uniregistry.net",
		"monash":                   "whois.monash.aridnrs.net.au",
		"money":                    "whois.donuts.co",
		"montblanc":                "whois.nic.montblanc",
		"mormon":                   "whois.afilias-srs.net",
		"mortgage":                 "whois.rightside.co",
		"moscow":                   "whois.nic.moscow",
		"motorcycles":              "whois.afilias-srs.net",
		"mov":                      "domain-registry-whois.l.google.com",
		"movie":                    "whois.donuts.co",
		"movistar":                 "whois-fe.movistar.tango.knipp.de",
		"mp":                       "whois.nic.mp",
		"ms":                       "whois.nic.ms",
		"mt":                       "whois.nic.mt",
		"mtn":                      "whois.nic.mtn",
		"mtpc":                     "whois.nic.gmo",
		"mtr":                      "whois.nic.mtr",
		"mu":                       "whois.nic.mu",
		"museum":                   "whois.museum",
		"mutuelle":                 "whois-mutuelle.nic.fr",
		"mx":                       "whois.mx",
		"my":                       "whois.domainregistry.my",
		"mz":                       "whois.nic.mz",
		"na":                       "whois.na-nic.com.na",
		"nadex":                    "whois.nic.nadex",
		"nagoya":                   "whois.nic.nagoya",
		"name":                     "whois.nic.name",
		"navy":                     "whois.rightside.co",
		"nc":                       "whois.nc",
		"nec":                      "whois.nic.nec",
		"net":                      "whois.verisign-grs.com",
		"netbank":                  "whois.nic.netbank",
		"network":                  "whois.donuts.co",
		"neustar":                  "whois.nic.neustar",
		"new":                      "domain-registry-whois.l.google.com",
		"news":                     "whois.rightside.co",
		"nexus":                    "domain-registry-whois.l.google.com",
		"nf":                       "whois.nic.net.nf",
		"ng":                       "whois.nic.net.ng",
		"ngo":                      "whois.publicinterestregistry.net",
		"nhk":                      "whois.nic.nhk",
		"nico":                     "whois.nic.gmo",
		"ninja":                    "whois.unitedtld.com",
		"nissan":                   "whois.nic.gmo",
		"nl":                       "whois.domain-registry.nl",
		"no":                       "whois.norid.no",
		"nokia":                    "whois.afilias-srs.net",
		"norton":                   "whois.nic.norton",
		"nowruz":                   "whois.agitsys.net",
		"nra":                      "whois.afilias-srs.net",
		"nrw":                      "whois-fe1.pdt.nrw.tango.knipp.de",
		"ntt":                      "whois.nic.ntt",
		"nu":                       "whois.nic.nu",
		"nyc":                      "whois.nic.nyc",
		"nz":                       "whois.srs.net.nz",
		"obi":                      "whois.nic.obi",
		"office":                   "whois.nic.office",
		"okinawa":                  "whois.nic.okinawa",
		"om":                       "whois.registry.om",
		"omega":                    "whois.nic.omega",
		"one":                      "whois.nic.one",
		"ong":                      "whois.publicinterestregistry.net",
		"onl":                      "whois.afilias-srs.net",
		"online":                   "whois.centralnic.com",
		"ooo":                      "whois.nic.ooo",
		"oracle":                   "whois.nic.oracle",
		"orange":                   "whois.nic.orange",
		"org":                      "whois.pir.org",
		"organic":                  "whois.afilias.net",
		"osaka":                    "whois.nic.osaka",
		"otsuka":                   "whois.nic.otsuka",
		"ovh":                      "whois-ovh.nic.fr",
		"page":                     "domain-registry-whois.l.google.com",
		"panerai":                  "whois.nic.panerai",
		"paris":                    "whois-paris.nic.fr",
		"pars":                     "whois.agitsys.net",
		"partners":                 "whois.donuts.co",
		"parts":                    "whois.donuts.co",
		"party":                    "whois.nic.party",
		"pe":                       "kero.yachay.pe",
		"pet":                      "whois.afilias.net",
		"pf":                       "whois.registry.pf",
		"pharmacy":                 "whois.nic.pharmacy",
		"philips":                  "whois.nic.philips",
		"photo":                    "whois.uniregistry.net",
		"photography":              "whois.donuts.co",
		"photos":                   "whois.donuts.co",
		"physio":                   "whois.nic.physio",
		"piaget":                   "whois.nic.piaget",
		"pics":                     "whois.uniregistry.net",
		"pictet":                   "whois.nic.pictet",
		"pictures":                 "whois.donuts.co",
		"pin":                      "whois.nic.pin",
		"ping":                     "whois.nic.ping",
		"pink":                     "whois.afilias.net",
		"pizza":                    "whois.donuts.co",
		"pl":                       "whois.dns.pl",
		"place":                    "whois.donuts.co",
		"play":                     "whois.nic.google",
		"playstation":              "whois.nic.playstation",
		"plumbing":                 "whois.donuts.co",
		"plus":                     "whois.donuts.co",
		"pm":                       "whois.nic.pm",
		"pohl":                     "whois.ksregistry.net",
		"poker":                    "whois.afilias.net",
		"porn":                     "whois.afilias-srs.net",
		"post":                     "whois.dotpostregistry.net",
		"pr":                       "whois.nic.pr",
		"praxi":                    "whois.nic.praxi",
		"press":                    "whois.centralnic.com",
		"pro":                      "whois.registrypro.pro",
		"prod":                     "domain-registry-whois.l.google.com",
		"productions":              "whois.donuts.co",
		"prof":                     "domain-registry-whois.l.google.com",
		"properties":               "whois.donuts.co",
		"property":                 "whois.uniregistry.net",
		"protection":               "whois.centralnic.com",
		"pt":                       "whois.dns.pt",
		"pub":                      "whois.unitedtld.com",
		"pw":                       "whois.nic.pw",
		"qa":                       "whois.registry.qa",
		"qpon":                     "whois.nic.qpon",
		"quebec":                   "whois.quebec.rs.corenic.net",
		"racing":                   "whois.nic.racing",
		"re":                       "whois.nic.re",
		"read":                     "whois.nic.read",
		"realtor":                  "whois.nic.realtor",
		"realty":                   "whois.centralnic.com",
		"recipes":                  "whois.donuts.co",
		"red":                      "whois.afilias.net",
		"redstone":                 "whois.afilias-srs.net",
		"rehab":                    "whois.rightside.co",
		"reise":                    "whois.reise.tld-box.at",
		"reisen":                   "whois.donuts.co",
		"reit":                     "whois.centralnic.com",
		"ren":                      "whois.nic.ren",
		"rent":                     "whois.centralnic.com",
		"rentals":                  "whois.donuts.co",
		"repair":                   "whois.donuts.co",
		"report":                   "whois.donuts.co",
		"republican":               "whois.rightside.co",
		"rest":                     "whois.centralnic.com",
		"restaurant":               "whois.donuts.co",
		"review":                   "whois.nic.review",
		"reviews":                  "whois.unitedtld.com",
		"rich":                     "whois.afilias-srs.net",
		"ricoh":                    "whois.nic.ricoh",
		"rio":                      "whois.gtlds.nic.br",
		"rip":                      "whois.rightside.co",
		"ro":                       "whois.rotld.ro",
		"rocher":                   "whois.nic.rocher",
		"rocks":                    "whois.unitedtld.com",
		"rodeo":                    "whois-dub.mm-registry.com",
		"room":                     "whois.nic.room",
		"rs":                       "whois.rnids.rs",
		"rsvp":                     "domain-registry-whois.l.google.com",
		"ru":                       "whois.tcinet.ru",
		"ruhr":                     "whois.nic.ruhr",
		"run":                      "whois.donuts.co",
		"rwe":                      "whois.nic.rwe",
		"ryukyu":                   "whois.nic.ryukyu",
		"sa":                       "whois.nic.net.sa",
		"saarland":                 "whois.ksregistry.net",
		"safe":                     "whois.nic.safe",
		"sakura":                   "whois.nic.sakura",
		"sale":                     "whois.rightside.co",
		"salon":                    "whois.donuts.co",
		"samsung":                  "whois.nic.samsung",
		"sandvik":                  "whois.nic.sandvik",
		"sandvikcoromant":          "whois.nic.sandvikcoromant",
		"sanofi":                   "whois.nic.sanofi",
		"sap":                      "whois.nic.sap",
		"sapo":                     "whois.nic.sapo",
		"sarl":                     "whois.donuts.co",
		"saxo":                     "whois.aridnrs.net.au",
		"sb":                       "whois.nic.net.sb",
		"sbs":                      "whois.nic.sbs",
		"sc":                       "whois2.afilias-grs.net",
		"sca":                      "whois.nic.sca",
		"scb":                      "whois.nic.scb",
		"schmidt":                  "whois.nic.schmidt",
		"scholarships":             "whois.afilias-srs.net",
		"school":                   "whois.donuts.co",
		"schule":                   "whois.donuts.co",
		"schwarz":                  "whois.nic.schwarz",
		"science":                  "whois.nic.science",
		"scor":                     "whois.nic.scor",
		"scot":                     "whois.scot.coreregistry.net",
		"se":                       "whois.iis.se",
		"seat":                     "whois.nic.seat",
		"security":                 "whois.centralnic.com",
		"seek":                     "whois.nic.seek",
		"sener":                    "whois.nic.sener",
		"services":                 "whois.donuts.co",
		"seven":                    "whois.nic.seven",
		"sew":                      "whois.afilias-srs.net",
		"sex":                      "whois.afilias-srs.net",
		"sexy":                     "whois.uniregistry.net",
		"sfr":                      "whois.nic.sfr",
		"sg":                       "whois.sgnic.sg",
		"sh":                       "whois.nic.sh",
		"sharp":                    "whois.nic.gmo",
		"shia":                     "whois.agitsys.net",
		"shiksha":                  "whois.afilias.net",
		"shoes":                    "whois.donuts.co",
		"show":                     "whois.donuts.co",
		"shriram":                  "whois.afilias-srs.net",
		"si":                       "whois.arnes.si",
		"singles":                  "whois.donuts.co",
		"site":                     "whois.centralnic.com",
		"sk":                       "whois.sk-nic.sk",
		"ski":                      "whois.ksregistry.net",
		"sky":                      "whois.nic.sky",
		"skype":                    "whois.nic.skype",
		"sl":                       "whois.nic.sl",
		"sm":                       "whois.nic.sm",
		"smile":                    "whois.nic.smile",
		"sn":                       "whois.nic.sn",
		"sncf":                     "whois-sncf.nic.fr",
		"so":                       "whois.nic.so",
		"soccer":                   "whois.donuts.co",
		"social":                   "whois.unitedtld.com",
		"software":                 "whois.rightside.co",
		"sohu":                     "whois.nic.sohu",
		"solar":                    "whois.donuts.co",
		"solutions":                "whois.donuts.co",
		"sony":                     "whois.nic.sony",
		"soy":                      "domain-registry-whois.l.google.com",
		"space":                    "whois.centralnic.com",
		"spiegel":                  "whois.ksregistry.net",
		"spreadbetting":            "whois.nic.spreadbetting",
		"srl":                      "whois.afilias-srs.net",
		"st":                       "whois.nic.st",
		"stada":                    "whois.afilias-srs.net",
		"starhub":                  "whois.nic.starhub",
		"statoil":                  "whois.nic.statoil",
		"stc":                      "whois.centralnic.com",
		"stcgroup":                 "whois.centralnic.com",
		"stockholm":                "whois.afilias-srs.net",
		"studio":                   "whois.rightside.co",
		"study":                    "whois.nic.study",
		"style":                    "whois.donuts.co",
		"su":                       "whois.tcinet.ru",
		"sucks":                    "whois.nic.sucks",
		"supplies":                 "whois.donuts.co",
		"supply":                   "whois.donuts.co",
		"support":                  "whois.donuts.co",
		"surf":                     "whois-dub.mm-registry.com",
		"surgery":                  "whois.donuts.co",
		"suzuki":                   "whois.nic.suzuki",
		"swatch":                   "whois.nic.swatch",
		"swiss":                    "whois.nic.swiss",
		"sx":                       "whois.sx",
		"sy":                       "whois.tld.sy",
		"sydney":                   "whois.nic.sydney",
		"symantec":                 "whois.nic.symantec",
		"systems":                  "whois.donuts.co",
		"tab":                      "whois.nic.tab",
		"taipei":                   "whois.nic.taipei",
		"tatamotors":               "whois.nic.tatamotors",
		"tatar":                    "212.193.111.5",
		"tattoo":                   "whois.uniregistry.net",
		"tax":                      "whois.donuts.co",
		"taxi":                     "whois.donuts.co",
		"tc":                       "whois.adamsnames.tc",
		"tci":                      "whois.agitsys.net",
		"team":                     "whois.donuts.co",
		"tech":                     "whois.centralnic.com",
		"technology":               "whois.donuts.co",
		"tel":                      "whois.nic.tel",
		"telefonica":               "whois-fe.telefonica.tango.knipp.de",
		"temasek":                  "whois.afilias-srs.net",
		"tennis":                   "whois.donuts.co",
		"tf":                       "whois.nic.tf",
		"tg":                       "whois.nic.tg",
		"th":                       "whois.thnic.co.th",
		"thd":                      "whois.afilias-srs.net",
		"theater":                  "whois.donuts.co",
		"theatre":                  "whois.centralnic.com",
		"tickets":                  "whois.centralnic.com",
		"tienda":                   "whois.donuts.co",
		"tips":                     "whois.donuts.co",
		"tires":                    "whois.donuts.co",
		"tirol":                    "whois.tirol.tld-box.at",
		"tk":                       "whois.dot.tk",
		"tl":                       "whois.nic.tl",
		"tm":                       "whois.nic.tm",
		"tn":                       "whois.ati.tn",
		"to":                       "whois.tonic.to",
		"today":                    "whois.donuts.co",
		"tokyo":                    "whois.nic.tokyo",
		"tools":                    "whois.donuts.co",
		"top":                      "whois.nic.top",
		"toray":                    "whois.nic.toray",
		"toshiba":                  "whois.nic.gmo",
		"tours":                    "whois.donuts.co",
		"town":                     "whois.donuts.co",
		"toyota":                   "whois.nic.toyota",
		"toys":                     "whois.donuts.co",
		"tr":                       "whois.nic.tr",
		"trade":                    "whois.nic.trade",
		"trading":                  "whois.nic.trading",
		"training":                 "whois.donuts.co",
		"travel":                   "whois.nic.travel",
		"travelers":                "whois.afilias-srs.net",
		"trust":                    "whois.nic.trust",
		"tui":                      "whois.ksregistry.net",
		"tv":                       "tvwhois.verisign-grs.com",
		"tw":                       "whois.twnic.net.tw",
		"tz":                       "whois.tznic.or.tz",
		"ua":                       "whois.ua",
		"ubs":                      "whois.nic.ubs",
		"ug":                       "whois.co.ug",
		"uk":                       "whois.nic.uk",
		"university":               "whois.donuts.co",
		"uno":                      "whois.nic.uno",
		"uol":                      "whois.gtlds.nic.br",
		"us":                       "whois.nic.us",
		"uy":                       "whois.nic.org.uy",
		"uz":                       "whois.cctld.uz",
		"vacations":                "whois.donuts.co",
		"vana":                     "whois.nic.vana",
		"vc":                       "whois2.afilias-grs.net",
		"ve":                       "whois.nic.ve",
		"vegas":                    "whois.afilias-srs.net",
		"ventures":                 "whois.donuts.co",
		"verisign":                 "whois.nic.verisign",
		"versicherung":             "whois.versicherung.tld-box.at",
		"vet":                      "whois.rightside.co",
		"vg":                       "whois.adamsnames.tc",
		"viajes":                   "whois.donuts.co",
		"video":                    "whois.rightside.co",
		"villas":                   "whois.donuts.co",
		"vin":                      "whois.donuts.co",
		"vip":                      "whois-dub.mm-registry.com",
		"virgin":                   "whois.nic.virgin",
		"vision":                   "whois.donuts.co",
		"vista":                    "whois.nic.vista",
		"vistaprint":               "whois.nic.vistaprint",
		"viva":                     "whois.centralnic.com",
		"vlaanderen":               "whois.vlaanderen.tld-box.at",
		"vodka":                    "whois-dub.mm-registry.com",
		"vote":                     "whois.afilias.net",
		"voting":                   "whois.voting.tld-box.at",
		"voto":                     "whois.afilias.net",
		"voyage":                   "whois.donuts.co",
		"vu":                       "vunic.vu",
		"wales":                    "whois.nic.wales",
		"walter":                   "whois.nic.walter",
		"wang":                     "whois.gtld.knet.cn",
		"watch":                    "whois.donuts.co",
		"webcam":                   "whois.nic.webcam",
		"website":                  "whois.centralnic.com",
		"wed":                      "whois.coccaregistry.org",
		"wedding":                  "whois-dub.mm-registry.com",
		"weir":                     "whois.nic.weir",
		"wf":                       "whois.nic.wf",
		"whoswho":                  "whois.nic.whoswho",
		"wien":                     "whois.nic.wien",
		"wiki":                     "whois.nic.wiki",
		"williamhill":              "whois.nic.williamhill",
		"win":                      "whois.nic.win",
		"windows":                  "whois.nic.windows",
		"wine":                     "whois.donuts.co",
		"wme":                      "whois.centralnic.com",
		"work":                     "whois-dub.mm-registry.com",
		"works":                    "whois.donuts.co",
		"world":                    "whois.donuts.co",
		"ws":                       "whois.website.ws",
		"wtc":                      "whois.nic.wtc",
		"wtf":                      "whois.donuts.co",
		"xbox":                     "whois.nic.xbox",
		"xerox":                    "whois.nic.xerox",
		"xin":                      "whois.afilias-srs.net",
		"xn--11b4c3d":              "whois.nic.xn--11b4c3d",
		"xn--1qqw23a":              "whois.ngtld.cn",
		"xn--30rr7y":               "whois.nic.wang",
		"xn--3bst00m":              "whois.gtld.knet.cn",
		"xn--3ds443g":              "whois.afilias-srs.net",
		"xn--3e0b707e":             "whois.kr",
		"xn--3pxu8k":               "whois.nic.xn--3pxu8k",
		"xn--42c2d9a":              "whois.nic.xn--42c2d9a",
		"xn--45q11c":               "whois.nic.xn--45q11c",
		"xn--4gbrim":               "whois.afilias-srs.net",
		"xn--55qw42g":              "whois.conac.cn",
		"xn--55qx5d":               "whois.ngtld.cn",
		"xn--6frz82g":              "whois.afilias.net",
		"xn--6qq986b3xl":           "whois.gtld.knet.cn",
		"xn--80adxhks":             "whois.nic.xn--80adxhks",
		"xn--80ao21a":              "whois.nic.kz",
		"xn--80asehdb":             "whois.online.rs.corenic.net",
		"xn--80aswg":               "whois.site.rs.corenic.net",
		"xn--90a3ac":               "whois.rnids.rs",
		"xn--90ais":                "whois.cctld.by",
		"xn--9dbq2a":               "whois.nic.xn--9dbq2a",
		"xn--9et52u":               "whois.nic.wang",
		"xn--b4w605ferd":           "whois.afilias-srs.net",
		"xn--c1avg":                "whois.publicinterestregistry.net",
		"xn--c2br7g":               "whois.nic.xn--c2br7g",
		"xn--cg4bki":               "whois.kr",
		"xn--clchc0ea0b2g2a9gcd":   "whois.sgnic.sg",
		"xn--czr694b":              "whois.nic.xn--czr694b",
		"xn--czrs0t":               "whois.donuts.co",
		"xn--czru2d":               "whois.gtld.knet.cn",
		"xn--d1acj3b":              "whois.nic.xn--d1acj3b",
		"xn--d1alf":                "whois.marnet.mk",
		"xn--efvy88h":              "whois.nic.xn--efvy88h",
		"xn--estv75g":              "whois.afilias-srs.net",
		"xn--fhbei":                "whois.nic.xn--fhbei",
		"xn--fiq228c5hs":           "whois.afilias-srs.net",
		"xn--fiq64b":               "whois.gtld.knet.cn",
		"xn--fiqs8s":               "cwhois.cnnic.cn",
		"xn--fiqz9s":               "cwhois.cnnic.cn",
		"xn--fjq720a":              "whois.donuts.co",
		"xn--flw351e":              "domain-registry-whois.l.google.com",
		"xn--hxt814e":              "whois.nic.xn--hxt814e",
		"xn--i1b6b1a6a2e":          "whois.publicinterestregistry.net",
		"xn--imr513n":              "whois.nic.xn--imr513n",
		"xn--io0a7i":               "whois.ngtld.cn",
		"xn--j1aef":                "whois.nic.xn--j1aef",
		"xn--j1amh":                "whois.dotukr.com",
		"xn--j6w193g":              "whois.hkirc.hk",
		"xn--kcrx77d1x4a":          "whois.nic.xn--kcrx77d1x4a",
		"xn--kprw13d":              "whois.twnic.net.tw",
		"xn--kpry57d":              "whois.twnic.net.tw",
		"xn--kput3i":               "whois.afilias-srs.net",
		"xn--lgbbat1ad8j":          "whois.nic.dz",
		"xn--mgb9awbf":             "whois.registry.om",
		"xn--mgba3a3ejt":           "whois.nic.xn--mgba3a3ejt",
		"xn--mgba3a4f16a":          "whois.nic.ir",
		"xn--mgbaam7a8h":           "whois.aeda.net.ae",
		"xn--mgbab2bd":             "whois.bazaar.coreregistry.net",
		"xn--mgberp4a5d4ar":        "whois.nic.net.sa",
		"xn--mgbt3dhd":             "whois.agitsys.net",
		"xn--mgbtx2b":              "whois.cmc.iq",
		"xn--mgbx4cd0ab":           "whois.domainregistry.my",
		"xn--mk1bu44c":             "whois.nic.xn--mk1bu44c",
		"xn--mxtq1m":               "whois.nic.xn--mxtq1m",
		"xn--ngbc5azd":             "whois.xn--ngbc5azd.aridnrs.net.au",
		"xn--node":                 "whois.itdc.ge",
		"xn--nqv7f":                "whois.publicinterestregistry.net",
		"xn--nqv7fs00ema":          "whois.publicinterestregistry.net",
		"xn--nyqy26a":              "whois.nic.xn--nyqy26a",
		"xn--o3cw4h":               "whois.thnic.co.th",
		"xn--ogbpf8fl":             "whois.tld.sy",
		"xn--p1acf":                "whois.nic.xn--p1acf",
		"xn--p1ai":                 "whois.tcinet.ru",
		"xn--pssy2u":               "whois.nic.xn--pssy2u",
		"xn--q9jyb4c":              "domain-registry-whois.l.google.com",
		"xn--qcka1pmc":             "domain-registry-whois.l.google.com",
		"xn--rhqv96g":              "whois.nic.xn--rhqv96g",
		"xn--ses554g":              "whois.nic.xn--ses554g",
		"xn--t60b56a":              "whois.nic.xn--t60b56a",
		"xn--tckwe":                "whois.nic.xn--tckwe",
		"xn--unup4y":               "whois.donuts.co",
		"xn--vermgensberater-ctb":  "whois.ksregistry.net",
		"xn--vermgensberatung-pwb": "whois.ksregistry.net",
		"xn--vhquv":                "whois.donuts.co",
		"xn--vuq861b":              "whois.ngtld.cn",
		"xn--wgbl6a":               "whois.registry.qa",
		"xn--xhq521b":              "whois.ngtld.cn",
		"xn--y9a3aq":               "whois.amnic.net",
		"xn--yfro4i67o":            "whois.sgnic.sg",
		"xn--ygbi2ammx":            "whois.pnina.ps",
		"xn--zfr164b":              "whois.conac.cn",
		"xperia":                   "whois.nic.xperia",
		"xxx":                      "whois.nic.xxx",
		"xyz":                      "whois.nic.xyz",
		"yachts":                   "whois.afilias-srs.net",
		"yamaxun":                  "whois.nic.yamaxun",
		"yandex":                   "whois.nic.yandex",
		"yodobashi":                "whois.nic.gmo",
		"yoga":                     "whois-dub.mm-registry.com",
		"yokohama":                 "whois.nic.yokohama",
		"youtube":                  "domain-registry-whois.l.google.com",
		"yt":                       "whois.nic.yt",
		"zara":                     "whois.afilias-srs.net",
		"zero":                     "whois.nic.zero",
		"zip":                      "domain-registry-whois.l.google.com",
		"zm":                       "whois.nic.zm",
		"zone":                     "whois.donuts.co",
		"zuerich":                  "whois.ksregistry.net",
	}
)

const (
	// IANA_WHOIS_SERVER is iana whois server
	IANA_WHOIS_SERVER = "whois.iana.org"
	// DOMAIN_WHOIS_SERVER is tld whois server
	DOMAIN_WHOIS_SERVER = "whois-servers.net"
	// WHOIS_PORT is default whois port
	WHOIS_PORT = "43"
)

// Version returns package version
func Version() string {
	return "1.3.0"
}

// Author returns package author
func Author() string {
	return "[Li Kexian](https://www.likexian.com/)"
}

// License returns package license
func License() string {
	return "Licensed under the Apache License 2.0"
}

// Whois do the whois query and returns whois info
func Whois(domain string, servers ...string) (result string, err error) {
	var cancel context.CancelFunc
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	return WhoisContext(ctx, domain, servers...)
}

// WhoisContext does the whois query and returns whois info
func WhoisContext(ctx context.Context, domain string, servers ...string) (result string, err error) {
	if ctx == nil {
		return "", errors.New("nil context")
	}

	domain = strings.Trim(strings.TrimSpace(domain), ".")
	if domain == "" {
		err = fmt.Errorf("Domain is empty")
		return
	}

	result, err = query(ctx, domain, servers...)
	if err != nil {
		return
	}

	token := "Registrar WHOIS Server:"
	if IsIpv4(domain) {
		token = "whois:"
	}

	start := strings.Index(result, token)
	if start == -1 {
		return
	}

	start += len(token)
	end := strings.Index(result[start:], "\n")
	server := strings.TrimSpace(result[start : start+end])
	if server == "" {
		return
	}

	tmpResult, err := query(ctx, domain, server)
	if err != nil {
		return
	}

	result += tmpResult

	return
}

// query do the query
func query(ctx context.Context, domain string, servers ...string) (result string, err error) {
	server := IANA_WHOIS_SERVER
	if len(servers) == 0 || servers[0] == "" {
		domains := strings.Split(domain, ".")
		if len(domains) < 1 {
			return "", errors.New("invalid domain")
		}
		var ok bool
		ext := domains[len(domains)-1]
		server, ok = whoisRoot[ext]
		if !ok {
			if strings.Contains(ext, "/") {
				ext = strings.Split(ext, "/")[0]
			}
			server = ext + "." + DOMAIN_WHOIS_SERVER
		}
	} else {
		server = strings.ToLower(servers[0])
		if server == "whois.arin.net" {
			domain = "n + " + domain
		}
	}

	var d net.Dialer

	conn, e := d.DialContext(ctx, "tcp", net.JoinHostPort(server, WHOIS_PORT))
	if e != nil {
		err = e
		return
	}

	defer conn.Close()
	if deadline, ok := ctx.Deadline(); ok {
		_ = conn.SetReadDeadline(deadline)
	}

	_, err = conn.Write([]byte(domain + "\r\n"))
	if err != nil {
		return
	}

	buffer, err := ioutil.ReadAll(conn)
	if err != nil {
		return
	}

	result = string(buffer)

	return
}

// IsIpv4 returns string is an ipv4 ip
func IsIpv4(ip string) bool {
	i := net.ParseIP(ip)
	return i.To4() != nil
}
